/*
Nombre: Saldos a favor
Fecha:  30/08/2023  
Elaborado por: Jose Cruz 
Empresa encargada: Optima corporation
*/
SELECT
    SRV.SESUSUSC CUENTA,
    SUB.SUCADESC ESTRATO,
    GEI.DESCRIPTION TIPO_DOCUMENTO,
    GSUB.IDENTIFICATION CEDULA,
    GSUB.SUBSCRIBER_NAME SUSCRIPTOR,
    AB.ADDRESS DIRECCION,
    GEO.DESCRIPTION MUNICIPIO,
    SRV.SESUNUSE PRODUCTO,
    CAT.CATEDESC CATEGORIA,
    SRV.SESUSAFA SALDO_FAVOR
FROM
    SFBZ0800.SERVSUSC SRV,
    SFBZ0800.SUSCRIPC SUS,
    SFBZ0800.AB_ADDRESS AB,
    SFBZ0800.GE_GEOGRA_LOCATION GEO,
    SFBZ0800.GE_SUBSCRIBER GSUB,
    SFBZ0800.GE_IDENTIFICA_TYPE GEI,
    SFBZ0800.CATEGORI CAT,
    SFBZ0800.SUBCATEG SUB
WHERE
    SRV.SESUSUSC = SUS.SUSCCODI
    AND SUS.SUSCCLIE = GSUB.SUBSCRIBER_ID
    AND GSUB.IDENT_TYPE_ID=GEI.IDENT_TYPE_ID
    AND SRV.SESUCATE=SUB.SUCACATE
    AND SRV.SESUSUCA = SUB.SUCACODI
    AND SRV.SESUCATE =CAT.CATECODI
    AND SRV.SESUSUSC IN (:CONTRATO)--1098324	
    AND SUS.SUSCIDDI=AB.ADDRESS_ID
    AND AB.NEIGHBORTHOOD_ID=GEO.GEOGRAP_LOCATION_ID

;